#!/bin/sh

sudo apt-get update

# docker
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

sudo apt-get update
# docker engine
sudo apt-get install docker-ce docker-ce-cli containerd.io

# make it super user
sudo usermod -aG docker <your-user>

# compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# make it super user
sudo chmod +x /usr/local/bin/docker-compose


docker-compose --version

